---
jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: workload
    podWait: false
    cleanup: false
    waitWhenFinished: false
    objects:

    # Template of Gu Pods with fedora-stress-ng
      - objectTemplate: templates/guaranteed/service.yaml
        replicas: 1
      - objectTemplate: templates/guaranteed/configmap.yaml
        replicas: 2
      - objectTemplate: templates/guaranteed/secret.yaml
        replicas: 4
      - objectTemplate: templates/guaranteed/deployment.yaml
        replicas: 1
        inputVars:
          Image: {{ .FEDORA_STRESSNG_TEST_IMAGE }}
          volumes:
            - name: secret-1
              type: secret
            - name: secret-2
              type: secret
            - name: configmap-1
              type: configMap
            - name: configmap-2
              type: configMap
            - name: configmap-3
              type: configMap
            - name: configmap-4
              type: configMap

    # Template of Burstable pod with pvc
      - objectTemplate: templates/burstable/pv.yaml
        replicas: 2
      - objectTemplate: templates/burstable/pvc.yaml
        replicas: 2
      - objectTemplate: templates/burstable/deployment.yaml
        replicas: 1
        inputVars:
          Image: {{ .FEDORA_STRESSNG_TEST_IMAGE }}
          volumes:
            - name: pvc-claim-20gb-1
              type: persistentVolumeClaim
              path: /mnt/pvc-data
      - objectTemplate: templates/deployment-pv.yaml
        replicas: 1
      - objectTemplate: templates/deployment-pvc.yaml
        replicas: 1

    # Template of burstable pods with exec probes
      - objectTemplate: templates/webserver/server-deployment.yaml
        replicas: 10
        inputVars:
          Image: {{ .NGINX_TEST_IMAGE }}
      - objectTemplate: templates/webserver/service.yaml
        replicas: 10
      - objectTemplate: templates/webserver/client-deployment.yaml
        replicas: 10
        inputVars:
          Image: {{ .CURL_TEST_IMAGE }}

    # Templates of burstable pods with kubeapiserver reqs
      - objectTemplate: templates/kubectlapp/serviceaccount.yaml
        replicas: 10
      - objectTemplate: templates/kubectlapp/role.yaml
        replicas: 10
      - objectTemplate: templates/kubectlapp/rolebinding.yaml
        replicas: 10
      - objectTemplate: templates/kubectlapp/deployment.yaml
        replicas: 10
        inputVars:
          Image: {{ .KUBECTL_TEST_IMAGE }}
