apiVersion: v1
kind: Service
metadata:
  name: service-{{.Replica}}
spec:
  selector:
    service-label: du-workload-gu-{{.Replica}}
  ports:
    - port: {{ or .port 80 }}
      targetPort: {{ or .targetPort 80 }}
