apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-20gb-{{.Replica}}
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data"