apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-20gb-{{.Replica}}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi