kind: Deployment
apiVersion: apps/v1
metadata:
  name: curl-{{.Replica}}
spec:
  template:
    metadata:
      labels:
        name: curl-{{.Replica}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: curlapp
          image: "{{ .Image }}"
          command: ["sleep", "inf"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: WEBSERVER_HOSTNAME
              value: webserver-{{.Replica}}
            - name: WEBSERVER_PORT
              value: "8080"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          startupProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "curl ${WEBSERVER_HOSTNAME}:${WEBSERVER_PORT}"
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 600
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "curl ${WEBSERVER_HOSTNAME}:${WEBSERVER_PORT}"
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: curl-{{.Replica}}
  strategy:
    type: RollingUpdate
