kind: Deployment
apiVersion: apps/v1
metadata:
  name: webserver-{{.Replica}}
spec:
  template:
    metadata:
      labels:
        name: webserver-{{.Replica}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: webserver
        image: "{{ .Image }}"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: webserver-{{.Replica}}
  strategy:
    type: RollingUpdate
