apiVersion: v1
kind: Secret
metadata:
  {{ if eq .group nil }}
  name: secret-{{ .group }}-{{.Replica}}
  {{ else }}
  name: secret-{{.Replica}}
  {{ end }}
type: Opaque
data:
  password: Zm9vb29vb29vb29vb29vbwo=
